language: python
# Test against 2.7
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
services:
  - postgresql
addons:
  apt:
    packages:
    - nodejs
    - gifsicle
env:
  PIP_DOWNLOAD_CACHE=$HOME/.cache/pip
  DATABASE_URL=pgsql://postgres:@localhost:5432/connect
  CACHE_URL=dummycache://
  SECRET_KEY=demo_secret_key
  EMAIL_SECRET_KEY=demo_email_secret_key
  CELERY_ALWAYS_EAGER=True
  TZ=US/Central
before_install:
   # Install command-line node packages before installing package apps & use
   # latest pip
   - npm install -g grunt-cli
   - npm install -g bower
   - pip install --upgrade pip
install:
  - npm install
  - bower install
  - pip install -r common-requirements.txt
# command to run tests
script:
  - python manage.py test
  - grunt jasmine
# install and run pylint if everything passed
after_success:
  - pip install pylint==1.4.4
  - pylint --rcfile=$HOME/.pylintrc connect_extras open_connect connect
# turn off email notifications
notifications:
  email: false
